from aiko2.core import Conversation, Message
from abc import ABC, abstractmethod
from .retrieval_results import RetrievalResults, Query
import sentence_transformers
import numpy as np
import rank_bm25


class BaseRetriever(ABC):
    """
    Base class for a retriever.
    A retriever retrieves information based on the queries generated by the evaluator.
    """
    
    
    @abstractmethod
    def retrieve(self, conversation:Conversation, queries:list[Query]) -> RetrievalResults:
        """
        Retrieve information based on the queries generated by the evaluator.
        
        Parameters
        ----------
        conversation : Conversation
            The conversation to retrieve information for.
        queries : List[Query]
            A list of queries to retrieve information.
        
        Returns
        -------
        RetrievalResults
            The retrieval context containing the results of the retrieval operation.
        """
        pass