from aiko2.core import Conversation, Message
from abc import ABC, abstractmethod
from .retrieval_results import RetrievalResults, Query
import sentence_transformers
import numpy as np
import rank_bm25


class BaseRetriever(ABC):
    """
    Base class for a retriever.
    A retriever retrieves information based on the queries generated by the evaluator.
    """
    
    
    @abstractmethod
    def retrieve(self, conversation:Conversation, queries:list[Query]) -> RetrievalResults:
        """
        Retrieve information based on the queries generated by the evaluator.
        
        Parameters
        ----------
        conversation : Conversation
            The conversation to retrieve information for.
        queries : List[Query]
            A list of queries to retrieve information.
        
        Returns
        -------
        RetrievalResults
            The retrieval context containing the results of the retrieval operation.
        """
        pass

    def insert_string(self, string:str):
        """
        Insert a string into the retriever.
        This may or may not be implemented by the retriever.
        
        Parameters
        ----------
        string : str
            The string to insert.
        """
        raise NotImplementedError

    def insert_file(self, file:str):
        """
        Insert a file into the retriever.
        This may or may not be implemented by the retriever.
        
        Parameters
        ----------
        file : str
            The file to insert.
        """
        raise NotImplementedError

    def insert_directory(self, directory:str):
        """
        Insert a directory into the retriever.
        This may or may not be implemented by the retriever.
        
        Parameters
        ----------
        directory : str
            The directory to insert.
        """
        raise NotImplementedError