from aiko.core import Conversation, Message
from abc import ABC, abstractmethod

class BaseRefiner(ABC):
    """
    Base class for refiners.
    Refiners are used to refine responses generated by the generator.
    """
    @abstractmethod
    def refine(self, conversation: Conversation, response: Message) -> Message:
        """
        Refine the response generated by the generator.

        Parameters
        ----------
        conversation : Conversation
            The conversation object containing the context of the conversation.
        response : Message
            The response generated by the generator.

        Returns
        -------
        Message
            The refined response.
        """
        pass